### PR TITLE
Add Alist Example: Populating from a paired list

### PR DESCRIPTION
**Pull request by mtekman**
I spent some time trying to understand how to initialise and append to an alist. Below is some self-contained code which I think would be useful to others.

### CODE REVIEW

**Comment by alphapapa** [comment]
Thanks, but I feel like this example may be too complicated.  For example, `seq-group-by` can be used as an initial pass that groups the items, like:

```el
(->> '(("fruit" "apple") ("veg" "cucumber") ("fruit" "banana")
       ("veg" "cabbage") ("fruit" "orange") ("fruit" "grapes"))
     (seq-group-by #'car))
;; (("veg" ("veg" "cucumber") ("veg" "cabbage"))
;;  ("fruit" ("fruit" "apple") ("fruit" "banana") ("fruit" "orange") ("fruit" "grapes")))
```

Then a fairly simple `--map` can be used to replace each pair with its second element, like:
```el
(->> '(("fruit" "apple") ("veg" "cucumber") ("fruit" "banana")
       ("veg" "cabbage") ("fruit" "orange") ("fruit" "grapes"))
     (seq-group-by #'car)
     (--map (cons (car it) (-map #'cadr (cdr it)))))
;;=> (("veg" "cucumber" "cabbage") ("fruit" "apple" "banana" "orange" "grapes"))
```

**Comment by mtekman** [comment]
That is amazing -- I still think it's an interesting use case to have in your handbook, since a rookie like myself would no doubt go looking for a way to do this and probably end up doing it my slow way.

Can you please place your above code snippet into the handbook? I'm happy to cancel the PR for your code instead.

**Comment by alphapapa** [comment]
I'll consider adding this example somewhere in the handbook, but I think it's more of an example of list structure transformation than "alist population."  And in that way, it demonstrates the use of `seq-group-by` and `--map` more than anything alist-specific.

I think of this handbook as more of a guide on how to do things in Emacs-specific ways, not so much as a general guide to how Lisp works.  So in these examples, I show Emacs-specific functions and libraries and how they compare with other solutions.

So I think your example of "populating from a paired list" is a bit too specific in terms of use-case and a bit too general in terms of Lisp.  

It reads more like a StackOverflow question and answer for someone who's new to Lisp in general, so it might be more appropriate to post it on emacs.stackexchange.com (if you still want to use StackExchange, anyway; I gave up on contributing anything significant to it a long time ago because of the way people with no domain-specific knowledge can reject material they're unqualified to judge.  However, emacs.SE has a good crowd of Emacs users, so you might still consider contributing to it).

You might also consider adding it to EmacsWiki.  Pretty much anything can go somewhere there.

What do you think?

Thanks.

**Comment by mtekman** [comment]
Yep, that sounds more than reasonable. Sorry, I just found your resource and I guess was treating it as the new Emacs wiki for all snippets which it is not nor should be haha!

I'll post this in the wiki, along with your code example if that's okay?

**Comment by alphapapa** [comment]
Please do!  Thanks for sharing it.

**Comment by mtekman** [comment]
Done, and thanks.

Feel free to edit:
 - https://www.emacswiki.org/emacs/List_Structure_Transformation

**Pull request closed without merging**
