### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by olnw**
I think this is a typo?

Change `copy-list` to `cl-copy-list`.

### CODE REVIEW

**Comment by alphapapa** [comment]
Not exactly a typo.  See 7c1898a7b93053cd0431f46f02d82c0a31bfb8bf in emacs.git.

Anyway, `cl` isn't loaded automatically or by default anymore, so the change is right to make, but it needs to be made in the Org file from which that Elisp file is tangled.

Thanks.

**Comment by olnw** [comment]
I tried changing it in README.org, and then exported the HTML file with `C-c C-e`. However it has also changed all of the HTML anchors, eg:
```
-<li><a href="#%5B%5Bhttps%3A%2F%2Fgithub.com%2Ftarsius%2Fkeycast%5D%5Bkeycast%3A%20Show%20current%20command%20and%20its%20key%20in%20the%20mode%20line%5D%5D">keycast: Show current command and its key in the mode line</a></li>
-<li><a href="#%5B%5Bhttps%3A%2F%2Fgithub.com%2Flewang%2Fcommand-log-mode%5D%5Bcommand-log-mode%3A%20log%20commands%20to%20buffer%5D%5D">command-log-mode: log commands to buffer</a></li>
+<li><a href="#orgd6e6a4b">keycast: Show current command and its key in the mode line</a></li>
+<li><a href="#orgd490fcd">command-log-mode: log commands to buffer</a></li>
```
Am I doing  this right?

**Comment by alphapapa** [comment]
It's probably due to a difference in the version of Org used, or maybe in that of `org-make-toc`.

Anyway, just change the Org file and I can export it again.

**Comment by olnw** [comment]
Just commenting in case you didn't see my last commit.

**Comment by alphapapa** [comment]
Thanks.  See also `copy-sequence`, `seq-copy`, etc.

**Pull request merged**
